const vendorsRecord = [
  {
    Month: "January",
    EggProfit: "80",
    FruitProfit: "70",
    VegProfit: "80",
    OverallProfit: "400",
    EggPercent: "20",
    FruitPercent: "20",
    VeggiesPercent: "20",
  },
  {
    Month: "February",
    EggProfit: "90",
    FruitProfit: "60",
    VegProfit: "50",
    OverallProfit: "470",
    EggPercent: "20",
    FruitPercent: "20",
    VeggiesPercent: "20",
  },
  {
    Month: "March",
    EggProfit: "",
    FruitProfit: "",
    VegProfit: "",
    OverallProfit: "",
    EggPercent: "",
    FruitPercent: "",
    VeggiesPercent: "",
  },
  {
    Month: "April",
    EggProfit: "80",
    FruitProfit: "70",
    VegProfit: "80",
    OverallProfit: "400",
    EggPercent: "20",
    FruitPercent: "20",
    VeggiesPercent: "20",
  },
];
